version: '3.4'

services:
  identity-server-sts:
    build:
      context: ./aspnet-core/services/Publish/identityserver
    volumes:
      - D:\Projects\Development\Abp\Application\logs\ids-sts:/app/Logs
    restart: always

  identity-server-admin:
    build:
      context: ./aspnet-core/services/Publish/identityserver4-admin
    volumes:
      - D:\Projects\Development\Abp\Application\logs\ids-admin:/app/Logs
    depends_on:
      - identity-server-sts
    restart: always

  admin-service:
    build:
      context: ./aspnet-core/services/Publish/admin
    volumes:
      - D:\Projects\Development\Abp\Application\logs\backend-admin:/app/Logs
    depends_on:
      - identity-server-sts
    restart: always

  localization-service:
    build:
      context: ./aspnet-core/services/Publish/localization
    volumes:
      - D:\Projects\Development\Abp\Application\logs\localization:/app/Logs
    restart: always

  platform-service:
    build:
      context: ./aspnet-core/services/Publish/platform
    volumes:
      - D:\Projects\Development\Abp\Application\logs\platform:/app/Logs
      - D:\Projects\Development\Abp\Application\data\platform:/app/file-blob-storing
    depends_on:
      - identity-server-sts
    restart: always

  messages-service:
    build:
      context: ./aspnet-core/services/Publish/messages
    volumes:
      - D:\Projects\Development\Abp\Application\logs\messages:/app/Logs
    depends_on:
      - identity-server-sts
    restart: always

  apigateway-admin-service:
    build:
      context: ./aspnet-core/services/Publish/apigateway-admin
    volumes:
      - D:\Projects\Development\Abp\Application\logs\apigateway-admin:/app/Logs
    depends_on:
      - identity-server-sts
      - admin-service
    restart: always

  apigateway-host-service:
    build:
      context: ./aspnet-core/services/Publish/apigateway-host
    volumes:
      - D:\Projects\Development\Abp\Application\logs\apigateway-host:/app/Logs
    depends_on:
      - identity-server-sts
      - apigateway-admin-service
    restart: always

volumes:
  dbdata:

networks:
  linyun-abp:
