version: '3.4'

services:
  sts-server:
    build:
      context: ./aspnet-core/services/Publish/identityserver
    volumes:
      - /var/opt/abp/logs/ids-sts:/app/Logs
      - /var/opt/abp/data/ids-sts/Modules:/app/Modules
    restart: always
    networks:
      - framework

  sts-api:
    build:
      context: ./aspnet-core/services/Publish/identityserver4-admin
    volumes:
      - /var/opt/abp/logs/ids-admin:/app/Logs
      - /var/opt/abp/data/ids-admin/Modules:/app/Modules
    depends_on:
      - sts-server
    restart: always
    networks:
      - framework

  admin-api:
    build:
      context: ./aspnet-core/services/Publish/admin
    volumes:
      - /var/opt/abp/logs/backend-admin:/app/Logs
      - /var/opt/abp/data/backend-admin/Modules:/app/Modules
    depends_on:
      - sts-server
    restart: always
    networks:
      - framework

  localization-api:
    build:
      context: ./aspnet-core/services/Publish/localization
    volumes:
      - /var/opt/abp/logs/localization:/app/Logs
      - /var/opt/abp/data/localization/Modules:/app/Modules
    restart: always
    depends_on:
      - sts-server
    networks:
      - framework

  platform-api:
    build:
      context: ./aspnet-core/services/Publish/platform
    volumes:
      - /var/opt/abp/logs/platform:/app/Logs
      - /var/opt/abp/data/platform/Modules:/app/Modules
      - /var/opt/abp/data/platform:/app/file-blob-storing
    depends_on:
      - sts-server
    restart: always
    networks:
      - framework

  messages-api:
    build:
      context: ./aspnet-core/services/Publish/messages
    volumes:
      - /var/opt/abp/logs/messages:/app/Logs
      - /var/opt/abp/data/messages/Modules:/app/Modules
    depends_on:
      - sts-server
    restart: always
    networks:
      - framework

  task-api:
    build:
      context: ./aspnet-core/services/Publish/task-management
    volumes:
      - /var/opt/abp/logs/task-management:/app/Logs
      - /var/opt/abp/data/task-management/Modules:/app/Modules
    depends_on:
      - sts-server
    restart: always
    networks:
      - framework

  internal-apigateway:
    build:
      context: ./aspnet-core/services/Publish/internal-apigateway
    volumes:
      - /var/opt/abp/logs/internal-apigateway:/app/Logs
      - /var/opt/abp/data/internal-apigateway/Modules:/app/Modules
    restart: always
    networks:
      - framework

networks:
  framework:
    external:
      name: ly_app_net
